# Generated by Django 3.2.9 on 2022-01-21 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220121_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorbooks',
            name='publication_yr',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 18, 56, 3, 321818, tzinfo=utc), verbose_name='Publication Year'),
        ),
    ]
