# Generated by Django 3.2.9 on 2022-01-21 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_authorbooks_publication_yr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorbooks',
            name='publication_yr',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 18, 57, 5, 43886, tzinfo=utc), verbose_name='Publication Year'),
        ),
    ]
