# Generated by Django 3.2.9 on 2022-01-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(choices=[('CIIT', 'Certificate In Information Technology'), ('CIJP', 'Certificate In Java Programming'), ('ADJT', 'Application Development Using Java Technologies'), ('BBTCJP', 'Bin Binary Certified Java Programmer'), ('CIWD', 'Certificate In Website Development'), ('AWD', 'Advanced Website Development'), ('CIPM', 'Certificate In PHP/MySQL Development'), ('ADWF', 'Android Development With Flutter'), ('BBCCP', 'Bin Binary Certified C++ Programmer'), ('DBA', 'Database Administrator [DBA] Oracle 12C'), ('CIDM', 'Certificate In Digital Marketing'), ('CIPP', 'Certificate In Python Programming'), ('BBTCFD', 'Bin Binary Certified Full Stack Developer With Python Django'), ('BBTCSE', 'Bin Binary Technologies Certified Software Engineer')], max_length=100, verbose_name='Course Name')),
                ('duration', models.IntegerField(choices=[('1', '2 Months'), ('2', '3 Months'), ('3', '4 Months'), ('4', '5 Months'), ('6', '6 Months'), ('7', '8 Months'), ('8', 'One Year')], verbose_name='Duration')),
                ('faculty', models.CharField(choices=[('1', 'Mr Basil Nzewure'), ('2', 'Stanley Surname'), ('3', 'Jude Nzewure'), ('4', 'Chioma Nzewure'), ('5', 'Theresa Nzewure')], max_length=200, verbose_name='Faculty')),
            ],
        ),
    ]
