# Generated by Django 3.2.9 on 2022-01-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(choices=[('MTH2', '2 Months'), ('MTH3', '3 Months'), ('MTH4', '4 Months'), ('MTH5', '5 Months'), ('MTH6', '6 Months'), ('MTH7', '8 Months'), ('MTH8', 'One Year')], verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='faculty',
            field=models.CharField(choices=[('Basil', 'Mr Basil Nzewure'), ('Stanley', 'Stanley Surname'), ('Jude', 'Jude Nzewure'), ('Chioma', 'Chioma Nzewure'), ('Theresa', 'Theresa Nzewure')], max_length=200, verbose_name='Faculty'),
        ),
    ]
