# Generated by Django 3.2.9 on 2022-01-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20220111_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(choices=[('MTH2', '2 Months'), ('MTH3', '3 Months'), ('MTH4', '4 Months'), ('MTH5', '5 Months'), ('MTH6', '6 Months'), ('MTH7', '8 Months'), ('MTH8', 'One Year')], max_length=100, verbose_name='Duration'),
        ),
    ]
