# Generated by Django 3.2.9 on 2022-01-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_bookcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(choices=[('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('8 Months', '8 Months'), ('One Year', 'One Year')], max_length=100, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='faculty',
            field=models.CharField(choices=[('Basil Nzewure', 'Mr Basil Nzewure'), ('Stanley Surname', 'Stanley Surname'), ('Jude Nzewure', 'Jude Nzewure'), ('Chioma Nzewure', 'Chioma Nzewure'), ('Theresa Nzewure', 'Theresa Nzewure')], max_length=200, verbose_name='Faculty'),
        ),
    ]
