# Generated by Django 3.2.9 on 2022-01-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20220111_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcourse',
            name='commence_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookcourse',
            name='end_date',
            field=models.DateField(),
        ),
    ]
